_BASE_: Base-BMask-R-CNN-FPN.yaml
MODEL:
  WEIGHTS: /home/Bxl/hujinwu/experience/IEMaskRCNNIEMaskRCNN/R-50-m.pkl
  MASK_ON: true
  RESNETS:
    DEPTH: 50
INPUT:
  MIN_SIZE_TRAIN: (800,)
TEST:
  EVAL_PERIOD: 60000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (480000, 640000)
  MAX_ITER: 720000
OUTPUT_DIR: "output/bmask_rcnn_r50_1x"
