_BASE_: Base-BMask-R-CNN-FPN.yaml
MODEL:
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
  MASK_ON: true
  RESNETS:
    DEPTH: 101
INPUT:
  MIN_SIZE_TRAIN: (800,)
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/bmask_rcnn_r101_3x"